## DNS
server {
  listen      53 udp;
  proxy_pass  172.30.5.13:53;
}

## VPN
server {
  listen      1194 udp;
  proxy_pass  172.30.5.11:1194;
}

## MQTT
server {
  listen      1883;
  proxy_pass  10.0.100.110:1883;
}
